Updates for recent Postgresql, centos8 changes
need to have centos7 for mysql community versions, can't
find e.g. 5.7 under centos8

dell machine is rebuilt

diff --git a/roles/postgresql/files/Dockerfile b/roles/postgresql/files/Dockerfile
--- a/roles/postgresql/files/Dockerfile
+++ b/roles/postgresql/files/Dockerfile
@@ -5,10 +5,24 @@ ARG repotag=9.6-3
 
 WORKDIR /opt
 
+# run huge locale dance:
+# https://stackoverflow.com/questions/58304278/how-to-fix-character-map-file-utf-8-not-found
+# https://unix.stackexchange.com/questions/140299/locale-gen-command-in-centos6
+# also seems to return a nonzero error code but it makes PG work below so just || true it
+RUN \
+	yum -y install glibc-locale-source glibc-langpack-en && \
+	localedef -v -c -i en_US -f UTF-8 en_US.UTF-8 || true
+
+
 RUN \
 	VERSION_TOKEN=`echo "${product_version}" | awk -F. '{ print $1$2 }'` && \
 	curl -OL https://download.postgresql.org/pub/repos/yum/${product_version}/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
 	rpm -i pgdg-redhat-repo-latest.noarch.rpm
+
+# centos8 thing
+# https://www.postgresql.org/download/linux/redhat/
+RUN dnf -qy module disable postgresql
+
 
 RUN \
 	VERSION_TOKEN=`echo "${product_version}" | awk -F. '{ print $1$2 }'` && \
